language: pt
pipeline: pretrained_embeddings_spacy
policies:
- name: MemoizationPolicy
  max_history: 3
- name: KerasPolicy
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.3
  core_threshold: 0.4
  fallback_action_name: 'utter_default'
